/*
 * File: app/store/LivesStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Metalorgie.store.LivesStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Metalorgie.model.Live'
    ],

    config: {
        groupTpl: '<div>{.:date("d/m/Y")}</div>',
        model: 'Metalorgie.model.Live',
        remoteSort: true,
        storeId: 'LivesStore',
        proxy: {
            type: 'jsonp',
            url: 'http://www.metalorgie.com/api/lives.php',
            reader: {
                type: 'json'
            }
        },
        grouper: {
            groupFn: function(item) {
                var dateParts = item.get('startDate').split("-");
                var jsDate = new Date(dateParts[0], dateParts[1] - 1, dateParts[2]);
                var store = item.stores[0];
                if (store.getGroupTpl()) {
                    return  new Ext.XTemplate(store.getGroupTpl()).apply(jsDate);
                }                
                return group;
            }
        }
    }
});