/*
 * File: app/view/NewsListContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Metalorgie.view.NewsListContainer', {
    extend: 'Ext.Container',
    alias: 'widget.newslistcontainer',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'list',
                id: 'newsDataList',
                itemTpl: [
                    '<tpl if="image.length &gt; 1">',
                    '<img class="photo" src="{image}" width="40" height="40"/>',
                    '</tpl>',
                    '<small>{texte}</small>'
                ],
                loadingText: 'Chargement...',
                store: 'NewsStore',
                grouped: true,
                pinHeaders: false,
                striped: true,
                plugins: [
                    {
                        autoPaging: true,
                        loadMoreText: 'Chargement des news',
                        type: 'listpaging'
                    }
                ]
            }
        ]
    }

});