/*
 * File: app/view/TabNav.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Metalorgie.view.TabNav', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.tabNav',

    requires: [
        'Metalorgie.view.NewsListContainer',
        'Metalorgie.view.ReleaseListContainer',
        'Metalorgie.view.LivesContainer'
    ],

    config: {
        centered: false,
        disabled: false,
        id: 'tabNav',
        items: [
            {
                xtype: 'container',
                title: 'News',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'newslistcontainer',
                        id: 'tabNewsContainer'
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Sorties',
                hidden: false,
                id: 'releasesTab',
                itemId: '',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'releaselistcontainer'
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Concerts',
                hidden: false,
                id: 'livesTab',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'livescontainer'
                    }
                ]
            }
        ]
    }

});